feeder: dataloader.feeder.BaseFeeder
phase: test
dataset: phoenix14
# dataset: phoenix14-si5
num_epoch: 60
work_dir: ./work_dir/TB_Net/
batch_size: 2
random_seed: 0
test_batch_size: 4
num_worker: 10
device: 0
log_interval: 2000
save_interval: 5

loss_weights:
  SeqCTC: 1.0
  IteLoss: 0.1
  ItaLoss: 10.0
#load_checkpoints: './work_dir/'
#load_weights: './work_dir/'

optimizer_args:
  optimizer: AdamW
  base_lr: 0.0001
  step: [ 20, 35]
  learning_ratio: 0.05
  weight_decay: 0.0001
  weight_ratio: 1000
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  num_gloss: -1

model: rec_net.SLRModel
decode_mode: beam
model_args:
  vit_type: ViT-B/16
